blogify/blogify/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
]

blogify/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group"),
]

blogify/posts/models.py
from django.db.models import (
    Model,
    TextField,
    DateTimeField,
    ForeignKey,
    CharField,
    SlugField,
    CASCADE,
    SET_NULL,
)
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(Model):
    title = CharField(max_length=200, verbose_name="Title")
    slug = SlugField(unique=True)
    description = TextField(verbose_name="Description")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Group"
        verbose_name_plural = "Groups"


class Post(Model):
    text = TextField(verbose_name="Post content")
    pub_date = DateTimeField(auto_now_add=True, verbose_name="Public date")
    author = ForeignKey(
        User, on_delete=CASCADE, related_name="posts", verbose_name="Author"
    )
    group = ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=SET_NULL,
        related_name="posts",
        verbose_name="Group",
    )

    class Meta:
        ordering = ["-pub_date"]
        verbose_name = "Post"
        verbose_name_plural = "Posts"

blogify/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group


def index(request):
    template = "posts/index.html"
    title = "Blogify"
    posts = Post.objects.order_by("-pub_date")[:10]
    context = {
        "posts": posts,
        "title": title,
        "text": title,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = "posts/group.html"
    posts = group.posts.all()
    context = {"group": group, "posts": posts}
    return render(request, template, context)

blogify/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1"
    />
    <link rel="icon" href={% static 'img/fav/fav.ico' %} type="image" /> <link
    rel="apple-touch-icon" sizes="180x180" href={% static 'img/fav/apple-touch-icon.png' %} /> <link
    rel="icon" type="image/png" sizes="32x32" href={% static 'img/fav/favicon-32x32.png' %} /> <link
    rel="icon" type="image/png" sizes="16x16" href={% static 'img/fav/favicon-16x16.png' %} />
    <meta
      name="msapplication-TileColor"
      content="#000"
    />
    <meta
      name="theme-color"
      content="#ffffff"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/bootstrap.min.css' %}"
    />
    {% block title %} Latest updates on the Website {% endblock %}
  </head>
  <body>
    <header>{% include 'includes/header.html' %}</header>
    <main>{% block content %} No data, no content :( {% endblock %}</main>
    <footer>{% include 'includes/footer.html' %}</footer>
  </body>
</html>

blogify/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© 2023 Copyright <span style="color: blue">Blog</span>ify</p>
</footer>

blogify/templates/includes/header.html
{% load static %}

<header>
  <nav
    class="navbar navbar-light"
    style="background-color: lightskyblue"
  >
    <div class="container">
      <a
        class="navbar-brand"
        href="{% url 'posts:index' %}"
      >
        <img src={% static 'img/logo.png' %} width="30" height="30" class="d-inline-block align-top"
        alt="" />
        <span style="color: blue">Blog</span>ify
      </a>
    </div>
  </nav>
</header>

blogify/templates/posts/group.html
{% extends 'base.html' %} {% block title %}
<title>{{ group.title }}</title>
{% endblock %} {% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in posts %}
  <article>
    <ul>
      <li>Author: {{ post.author.get_full_name }}</li>
      <li>Publication date: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
    <p>{{ post.text }}</p>
  </article>
  {% if not forloop.last %}
  <hr />
  {% endif %} {% endfor %}
  <a href="{% url 'posts:index' %}">Latest Updates on the Website</a>
</div>
{% endblock%}

blogify/templates/posts/index.html
{% extends 'base.html' %} {% block title %}
<title>{{ title }}</title>
{% endblock %} {% block content %}
<div class="container py-5">
  <h1>Latest Updates on the Website</h1>
  {% for post in posts %}
  <article>
    <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
    <p>{{ post.text }}</p>
    <a href={% url 'posts:posts' %}>все записи группы</a>
  </article>
  {% if not forloop.last %}
  <hr />
  {% endif %} {% endfor %}
</div>
{% endblock %}